-- Canonical market-only aggregate MA breadth snapshot. No account or execution coupling.
CREATE TABLE IF NOT EXISTS ma_breadth_snapshot_v1 (
    ma_breadth_snapshot_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    asof_ts_utc DATETIME(6) NOT NULL,
    venue VARCHAR(32) NOT NULL,
    universe_id VARCHAR(96) NOT NULL,
    universe_version VARCHAR(64) NOT NULL,
    universe_hash CHAR(64) NOT NULL,
    input_interval VARCHAR(16) NOT NULL,
    lookback_horizon VARCHAR(64) NOT NULL,
    effective_horizon VARCHAR(32) NOT NULL,
    freshness_status VARCHAR(32) NOT NULL,
    model_id VARCHAR(64) NOT NULL,
    model_version VARCHAR(16) NOT NULL,
    data_status VARCHAR(32) NOT NULL,
    eligible_count SMALLINT UNSIGNED NOT NULL,
    evaluated_count SMALLINT UNSIGNED NOT NULL,
    insufficient_history_count SMALLINT UNSIGNED NOT NULL,
    stale_constituent_count SMALLINT UNSIGNED NOT NULL,
    coverage_pct DECIMAL(7,4) NOT NULL,
    universe_above_sma50_count SMALLINT UNSIGNED NOT NULL,
    universe_above_sma50_pct DECIMAL(7,4) NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (ma_breadth_snapshot_id),
    UNIQUE KEY uq_ma_breadth_identity (asof_ts_utc, venue, universe_id, universe_version, universe_hash, input_interval, model_id, model_version),
    KEY idx_ma_breadth_latest (venue, model_id, model_version, asof_ts_utc),
    CONSTRAINT chk_ma_breadth_coverage CHECK (coverage_pct BETWEEN 0 AND 100),
    CONSTRAINT chk_ma_breadth_pct CHECK (universe_above_sma50_pct IS NULL OR universe_above_sma50_pct BETWEEN 0 AND 100),
    CONSTRAINT chk_ma_breadth_counts CHECK (evaluated_count + insufficient_history_count + stale_constituent_count = eligible_count),
    CONSTRAINT chk_ma_breadth_status CHECK (data_status IN ('AVAILABLE', 'INSUFFICIENT_DATA')),
    CONSTRAINT chk_ma_breadth_freshness CHECK (freshness_status IN ('UNKNOWN')),
    CONSTRAINT chk_ma_breadth_horizon CHECK (effective_horizon IN ('UNKNOWN'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
  COMMENT='Canonical market-only aggregate MA50 breadth; raw numeric primary output.';
