#!/usr/bin/env python3
from __future__ import annotations

import argparse
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import pandas as pd


def parse_args():
    parser = argparse.ArgumentParser(
        description="Plot one or more equity CSV files generated by run_advice_backtest_v2.py"
    )
    parser.add_argument("files", nargs="+", help="One or more equity CSV files")
    parser.add_argument("--output", required=True, help="Output PNG path")
    return parser.parse_args()


def main():
    args = parse_args()

    plt.figure(figsize=(12, 6))
    plotted = 0

    for file_path in args.files:
        path = Path(file_path)
        df = pd.read_csv(path)

        if df.empty or "equity_curve" not in df.columns:
            print(f"[SKIP] {path} empty or invalid")
            continue

        if "ts_utc" in df.columns:
            df["ts_utc"] = pd.to_datetime(df["ts_utc"], errors="coerce")
            x = df["ts_utc"]
        else:
            x = range(len(df))

        y = pd.to_numeric(df["equity_curve"], errors="coerce")
        label = df["policy_name"].iloc[0] if "policy_name" in df.columns and not df.empty else path.stem

        plt.plot(x, y, label=label)
        plotted += 1

    plt.title("Backtest Equity Curves")
    plt.xlabel("UTC time")
    plt.ylabel("Equity curve")
    plt.grid(True)

    if plotted > 0:
        plt.legend()

    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    plt.tight_layout()
    plt.savefig(output_path, dpi=140)
    print(f"[OK] saved: {output_path}")


if __name__ == "__main__":
    main()
