from __future__ import annotations

from dataclasses import dataclass


UNKNOWN_LABEL_DESCRIPTION = "No description registered yet."


@dataclass(frozen=True)
class LabelDescription:
    label: str
    description: str
    category: str = "general"
    axis_name: str | None = None
    axis_type: str | None = None
    axis_value: int | None = None
    human_label: str | None = None
    action_hint: str | None = None


def _entry(
    label: str,
    description: str,
    *,
    category: str = "general",
    axis_name: str | None = None,
    axis_type: str | None = None,
    axis_value: int | None = None,
    human_label: str | None = None,
    action_hint: str | None = None,
) -> LabelDescription:
    return LabelDescription(
        label=label,
        description=description,
        category=category,
        axis_name=axis_name,
        axis_type=axis_type,
        axis_value=axis_value,
        human_label=human_label,
        action_hint=action_hint,
    )


_REGISTRY: dict[str, LabelDescription] = {
    item.label: item
    for item in [
        _entry("REDUCE_CANDIDATE", "Review pressure for an existing holding. Not an automatic sell instruction.", category="position_review"),
        _entry("EXIT_CANDIDATE", "Stronger review pressure for an existing holding. Downstream permission is still required.", category="position_review"),
        _entry("HOLD_REVIEW", "Existing holding can be monitored. No manual trade action is implied.", category="position_review"),
        _entry("HOLD_DEFENSIVE", "Keep existing position under defensive context. Not a buy or sell instruction.", category="position_review"),
        _entry("MANUAL_REDUCE_CHECK", "Manual review needed after target/risk context. Not an automatic sell.", category="position_review"),
        _entry("MANUAL_CHECK", "User review needed. No automatic trade action.", category="position_review"),
        _entry(
            "POSITION_HOLD_REVIEW",
            "Position review state for an existing holding only. Hold review context, not entry readiness and not order permission.",
            category="position_review",
            human_label="Hold review",
        ),
        _entry(
            "POSITION_WAIT_FRESH_MAP",
            "Position review state for an existing holding only. Wait for a fresh map/advice before reviewing changes. Not entry readiness and not order permission.",
            category="position_review",
            human_label="Wait fresh map",
        ),
        _entry(
            "POSITION_MANUAL_REVIEW",
            "Position review state for an existing holding only. Manual review context, not entry readiness and not order permission.",
            category="position_review",
            human_label="Manual review",
        ),
        _entry(
            "POSITION_INCREASE_REVIEW",
            "Position review state for an existing holding only. Increase review context, not entry readiness and not order permission.",
            category="position_review",
            human_label="Increase review",
        ),
        _entry(
            "POSITION_EXIT_REVIEW",
            "Position review state for an existing holding only. Exit/reduce review context, not entry readiness and not order permission.",
            category="position_review",
            human_label="Exit review",
        ),
        _entry("TARGET_REACHED", "Mapped target or reaction zone has been reached or touched.", category="target_lifecycle"),
        _entry("TARGET_PENDING", "Mapped target has not been reached yet.", category="target_lifecycle"),
        _entry("TARGET_REACHED_STALE", "Target reached context exists, but the map may need refresh before relying on it.", category="target_lifecycle"),
        _entry("TARGET_TOUCHED_RECENTLY", "Latest lower-timeframe candle touched the target zone; price may already have moved away.", category="target_lifecycle"),
        _entry("EXTENSION_TOUCHED_INTRABAR", "Intrabar high/low touched the mapped extension or target zone.", category="target_lifecycle"),
        _entry("PULLBACK_AFTER_TARGET_TOUCH", "Target was touched intrabar and current price has pulled back from the touch.", category="target_lifecycle"),
        _entry("STALE_FOR_INTRABAR_DECISION", "Intrabar decision context is older than the freshness threshold; verify live chart before acting.", category="target_lifecycle"),
        _entry("TARGET_RETEST_SUPPORT", "Target retest/support context after an upside move. Market structure context only.", category="target_lifecycle"),
        _entry("POST_ENTRY_PROGRESS", "Price moved beyond the entry/reaction zone and is progressing toward the mapped target.", category="target_lifecycle"),
        _entry("ENTRY_WINDOW_PASSED", "Price has moved beyond the preferred entry window for the current map.", category="target_lifecycle"),
        _entry("PRICE_PROGRESS_PENDING", "Price has not progressed materially beyond the entry/reaction zone yet.", category="target_lifecycle"),
        _entry("DOWNSIDE_TARGET_APPROACHING", "Price is approaching the mapped downside target/support zone.", category="target_lifecycle"),
        _entry("DOWNSIDE_TARGET_NEAR", "Price is near the mapped downside target/support zone.", category="target_lifecycle"),
        _entry("RISK_NEAR", "Price is near a mapped risk/invalidation zone.", category="risk_market"),
        _entry("RISK_OK", "Risk/invalidation zone is not near at current price.", category="risk_market"),
        _entry("RECLAIM_NEAR", "Price is near a reclaim or invalidation boundary; fresh recompute may be needed.", category="risk_market"),
        _entry("RECLAIM_CONFIRMED", "Price has reclaimed a previous invalidation/reclaim level.", category="risk_market"),
        _entry("INVALIDATION_NEAR", "Price is near the mapped invalidation boundary.", category="risk_market"),
        _entry("MARKET_DAMAGE_CAUTION", "Market context is in caution band; blocks or limits new exposure depending on downstream rules.", category="risk_market"),
        _entry("MARKET_DAMAGE_RISK", "Market context is damaged; new exposure is blocked by risk context.", category="risk_market"),
        _entry("APLUS_AVOID", "External A+ context marks this asset as avoid/caution. It is context, not an order.", category="aplus_context"),
        _entry("APLUS_ANCHOR_CONTEXT", "External A+ context marks this as anchor/core context. It is not trade permission.", category="aplus_context"),
        _entry("APLUS_CANONICAL_CORE", "External A+ context marks this as stronger/core context. It is not trade permission.", category="aplus_context"),
        _entry("DO_NOT_ADD", "Do not increase this existing position under current context.", category="add_buy_setup"),
        _entry("NO_INCREASE", "Do not add to this existing position under current context.", category="add_buy_setup"),
        _entry("NO_NEW_BUY", "No new buy is allowed under current context.", category="add_buy_setup"),
        _entry(
            "BLOCKED_NO_NEW_BUY",
            "New buy is blocked. Check the displayed cause/unblock reason.",
            category="candidate_readiness",
            axis_name="candidate_readiness_pressure",
            axis_type="signed_int",
            axis_value=-6,
            human_label="No new buy",
            action_hint="New buy blocked",
        ),
        _entry("SETUP_FAILED", "Setup filter did not pass. This is not an entry.", category="add_buy_setup"),
        _entry("SETUP FAILED", "Setup filter did not pass. This is not an entry.", category="add_buy_setup"),
        _entry("SETUP_FAIL", "Setup filter did not pass. This is not an entry.", category="add_buy_setup"),
        _entry("SELECTION_STATE_NOT_ELIGIBLE", "Selection state is not eligible for promotion into a setup candidate.", category="add_buy_setup"),
        _entry("PAPER_BUY_READY", "Research/paper candidate only. Not live permission.", category="candidate_readiness"),
        _entry(
            "BUY_READY",
            "Market/setup side is ready for entry evaluation. Not order permission; decision_gate and execution_planner remain downstream.",
            category="candidate_readiness",
            axis_name="candidate_readiness_pressure",
            axis_type="signed_int",
            axis_value=10,
            human_label="Entry ready",
            action_hint="Market/setup ready only",
        ),
        _entry(
            "ENTRY_CANDIDATE",
            "Strong market/setup context for entry review, but not yet buy-ready.",
            category="candidate_readiness",
            axis_name="candidate_readiness_pressure",
            axis_type="signed_int",
            axis_value=8,
            human_label="Entry candidate",
            action_hint="Needs downstream permission",
        ),
        _entry(
            "BUY_CANDIDATE",
            "Positive market/setup candidate for later entry evaluation, but not yet entry-ready.",
            category="candidate_readiness",
            axis_name="candidate_readiness_pressure",
            axis_type="signed_int",
            axis_value=6,
            human_label="Buy candidate",
            action_hint="Positive context only",
        ),
        _entry(
            "WATCH_FOR_CONFIRMATION",
            "Candidate needs confirmation before any paper/live consideration.",
            category="candidate_readiness",
            axis_name="candidate_readiness_pressure",
            axis_type="signed_int",
            axis_value=4,
            human_label="Watch for confirmation",
            action_hint="Await confirmation",
        ),
        _entry(
            "CORE_CONTEXT",
            "Structurally relevant asset for market or portfolio context. Positive context, but not an entry trigger.",
            category="candidate_readiness",
            axis_name="candidate_readiness_pressure",
            axis_type="signed_int",
            axis_value=2,
            human_label="Core context",
            action_hint="Positive context only",
        ),
        _entry(
            "CONTEXT_ONLY",
            "Reference context only. Useful for comparison or monitoring, but not an entry-ready candidate.",
            category="candidate_readiness",
            axis_name="candidate_readiness_pressure",
            axis_type="signed_int",
            axis_value=1,
            human_label="Context only",
            action_hint="Reference context only",
        ),
        _entry(
            "WAIT",
            "Neutral state. No active entry setup, but not a hard avoid.",
            category="candidate_readiness",
            axis_name="candidate_readiness_pressure",
            axis_type="signed_int",
            axis_value=0,
            human_label="Wait / no setup yet",
            action_hint="Neutral wait",
        ),
        _entry(
            "WAIT_FOR_SETUP",
            "Neutral state. Setup is not active yet, but the asset is not blocked.",
            category="candidate_readiness",
            axis_name="candidate_readiness_pressure",
            axis_type="signed_int",
            axis_value=0,
            human_label="Wait / no setup yet",
            action_hint="Neutral wait",
        ),
        _entry(
            "BUY_REVIEW",
            "Manual paper-trading review for a possible buy. Market/setup context only; not order permission.",
            category="candidate_readiness",
            human_label="buy review",
            action_hint="Manual entry review",
        ),
        _entry(
            "RELOAD_REVIEW",
            "Manual paper-trading review for a possible reload/add around support or retest context. Market-only readout; not account permission.",
            category="candidate_readiness",
            human_label="reload review",
            action_hint="Manual reload review",
        ),
        _entry(
            "TRIM_REVIEW",
            "Manual paper-trading review for a possible trim near target or extension context. Not an automatic sell.",
            category="position_review",
            human_label="trim review",
            action_hint="Manual trim review",
        ),
        _entry(
            "REDUCE_REVIEW",
            "Manual review for reducing an existing position under poor risk or invalidated context. Not an automatic sell.",
            category="position_review",
            human_label="reduce review",
            action_hint="Manual reduce review",
        ),
        _entry(
            "NO_POSITION_LIFECYCLE_EDGE",
            "Existing position is visible, but the current lifecycle inputs do not surface a trim, reload, or reduce edge.",
            category="position_review",
            human_label="no lifecycle edge",
        ),
        _entry(
            "STALE_POSITION_SOURCE",
            "Current account-position snapshot is stale, so lifecycle review should not escalate beyond a stale-state warning.",
            category="data_quality",
            human_label="stale position source",
        ),
        _entry(
            "MISSING_PRICE",
            "Current public market price is missing, so lifecycle review cannot be evaluated reliably.",
            category="data_quality",
            human_label="missing price",
        ),
        _entry(
            "MISSING_POSITION",
            "No current position quantity is available for lifecycle review.",
            category="data_quality",
            human_label="missing position",
        ),
        _entry(
            "CAUTION",
            "Caution context. The asset is not a hard avoid, but setup/risk is not strong enough for entry readiness.",
            category="candidate_readiness",
            axis_name="candidate_readiness_pressure",
            axis_type="signed_int",
            axis_value=-3,
            human_label="Caution",
            action_hint="Limited context",
        ),
        _entry(
            "AVOID",
            "Unfavorable context. No new buy. Not an automatic full exit.",
            category="candidate_readiness",
            axis_name="candidate_readiness_pressure",
            axis_type="signed_int",
            axis_value=-10,
            human_label="Avoid / do not add",
            action_hint="Avoid new exposure",
        ),
        _entry(
            "INVALIDATED",
            "The displayed map is invalidated or stale enough that a fresh upstream recompute is required before acting.",
            category="recompute_lifecycle",
            human_label="invalidated",
            action_hint="Fresh map required",
        ),
        _entry(
            "BULLISH_SHORT_TERM",
            "Constructive short-term direction/readout based on current map proximity and available overlays. Display-only.",
            category="general",
            human_label="bullish short-term",
        ),
        _entry(
            "BULLISH_MEDIUM_TERM",
            "Constructive medium-term direction/readout with context support, but not near an immediate entry zone. Display-only.",
            category="general",
            human_label="bullish medium-term",
        ),
        _entry(
            "NEUTRAL_WAIT",
            "Neutral or incomplete context. Wait/read-only review state, not a positive or negative trigger.",
            category="general",
            human_label="neutral / wait",
        ),
        _entry(
            "BEARISH_RISK",
            "Risk-heavy or defensive direction/readout from the current map/context. Display-only.",
            category="general",
            human_label="bearish risk",
        ),
        _entry(
            "TRIM_CANDIDATE",
            "Current readout favors trim/harvest review rather than new add review. Display-only.",
            category="position_review",
            human_label="trim candidate",
        ),
        _entry(
            "RELOAD_CANDIDATE",
            "Current readout favors reload/support review rather than trim review. Display-only.",
            category="candidate_readiness",
            human_label="reload candidate",
        ),
        _entry(
            "FIBO_ZONE_RECLAIM_V1",
            "Display-only strategy-family inference for rows driven mainly by structural zone, fib, reclaim, or retest context.",
            category="candidate_readiness",
            human_label="Fibo zone reclaim v1",
        ),
        _entry(
            "REGIME_CONTEXT_V1",
            "Display-only strategy-family inference for rows driven mainly by market-breath or broader regime context.",
            category="candidate_readiness",
            human_label="Regime context v1",
        ),
        _entry(
            "BREATHLINE_CONTEXT_V1",
            "Display-only strategy-family inference for rows with explicit breathline context in current paper inputs.",
            category="candidate_readiness",
            human_label="Breathline context v1",
        ),
        _entry(
            "ROTATION_REVIEW_V1",
            "Display-only strategy-family inference for rows with explicit rotation-review context already present in current paper inputs.",
            category="position_review",
            human_label="Rotation review v1",
        ),
        _entry(
            "UNKNOWN_STRATEGY_CONTEXT",
            "Current paper inputs are insufficient to infer a specific strategy-family context conservatively.",
            category="data_quality",
            human_label="unknown strategy context",
        ),
        _entry(
            "SHORT_TERM_SPIKE",
            "Conservative horizon bucket for rows driven mainly by fast intrabar spike or extension context.",
            category="candidate_readiness",
            human_label="short-term spike",
        ),
        _entry(
            "MEDIUM_TERM_SWING",
            "Conservative horizon bucket for rows driven mainly by zone, reclaim, retest, or mapped swing context.",
            category="candidate_readiness",
            human_label="medium-term swing",
        ),
        _entry(
            "LONG_TERM_CYCLE",
            "Conservative horizon bucket for rows whose current policy or context explicitly points to a long-horizon view.",
            category="candidate_readiness",
            human_label="long-term cycle",
        ),
        _entry(
            "UNKNOWN_HORIZON",
            "Current paper inputs are insufficient to infer a specific horizon bucket conservatively.",
            category="data_quality",
            human_label="unknown horizon",
        ),
        _entry(
            "INSUFFICIENT_SAMPLE",
            "Not enough data/sample to determine candidate readiness reliably.",
            category="data_quality",
            human_label="Insufficient sample",
            action_hint="Data unknown",
        ),
        _entry("UNKNOWN", "State or context is unknown from the currently available data.", category="data_quality"),
        _entry("YES", "Positive/bool display marker. Context only.", category="general"),
        _entry("NO", "Negative/bool display marker. Context only.", category="general"),
        _entry("UP", "Up-leg / upside structural context.", category="general"),
        _entry("DOWN", "Down-leg / downside structural context.", category="general"),
        _entry("HIGH", "High severity / elevated caution display.", category="general"),
        _entry("ELEVATED", "Elevated review severity.", category="general"),
        _entry("FRESH", "Fresh context marker.", category="general"),
        _entry("STALE", "Stale context marker. Review with caution and prefer a fresh snapshot before acting.", category="general"),
        _entry("VERY_STALE", "Context is materially stale and should be treated cautiously.", category="general"),
        _entry("FRESH_MAP", "Map/advice snapshot is recent within the dashboard freshness threshold.", category="general"),
        _entry("MARKET_PRICE_SNAPSHOT", "Current value comes from the market price snapshot table.", category="general"),
        _entry("PRICE_SNAPSHOT_FRESH", "Latest market price snapshot is fresh within the intrabar context window.", category="general"),
        _entry("LTF_CANDLES_FRESH", "Lower-timeframe candle data is fresh for intrabar context.", category="general"),
        _entry("LTF_CANDLES_STALE", "Lower-timeframe candle data is stale for intrabar context.", category="general"),
        _entry("INTRABAR_ACTIVE", "Intrabar overlay is active against the current structural map.", category="general"),
        _entry("NO_INTRABAR_RECOMPUTE_HINT", "Intrabar overlay does not add an extra recompute hint right now.", category="general"),
        _entry("INTRABAR_RECOMPUTE_REVIEW", "Intrabar overlay suggests recompute review context.", category="general"),
        _entry("INTRABAR_MONITOR_RECOMPUTE", "Intrabar overlay suggests monitoring for a possible recompute.", category="general"),
        _entry("INTRABAR_INVALIDATION_TOUCHED", "Intrabar price touched the map invalidation boundary.", category="general"),
        _entry("INTRABAR_RECLAIM_TOUCHED", "Intrabar price touched a reclaim boundary.", category="general"),
        _entry("INTRABAR_RECLAIM_CONFIRMED", "Intrabar overlay confirms reclaim context.", category="general"),
        _entry("INTRABAR_TARGET_TOUCH_REVIEW", "Intrabar target touch should be reviewed before relying on follow-through.", category="general"),
        _entry("MISSING_CURRENT_PRICE", "Current public price snapshot is missing for this row.", category="data_quality", human_label="missing current price"),
        _entry("MISSING_PAPER_ADVICE", "Latest paper-advice context is missing for this row.", category="data_quality", human_label="missing paper advice"),
        _entry("MISSING_ENTRY_PRICE", "Average entry price is missing for this position row.", category="data_quality", human_label="missing entry price"),
        _entry("MISSING_TARGET_ZONE", "Target or reaction zone is missing for this row.", category="data_quality", human_label="missing target zone"),
        _entry("MISSING_ZONE_MAP", "Entry/target zone map is missing for this row.", category="data_quality", human_label="missing zone map"),
        _entry("MISSING_INVALIDATION", "Invalidation/risk level is missing for this row.", category="data_quality", human_label="missing invalidation"),
        _entry("MISSING_MARKET_BREATH_CONTEXT", "Market breath/context overlay is missing for this row.", category="data_quality", human_label="missing breath/context"),
        _entry("MISSING_INTRABAR_CONTEXT", "Lower-timeframe lifecycle overlay is missing for this row.", category="data_quality", human_label="missing intrabar context"),
        _entry("BROKER_PRIVATE_CALLS=0", "No private broker/API reads occur in this cockpit render.", category="safety"),
        _entry("BROKER_CALLS=0", "No direct broker/API calls occur in this cockpit render.", category="safety"),
        _entry("BROKER_WRITES=0", "No broker writes occur in this cockpit render.", category="safety"),
        _entry("ORDER_SUBMISSION=0", "No order submission occurs in this cockpit render.", category="safety"),
        _entry("EXECUTOR=NONE", "The executor is not used by this cockpit render.", category="safety"),
        _entry("LIVE_TRADING=FALSE", "Live trading is disabled for this cockpit render.", category="safety"),
        _entry("PAPER/MANUAL ONLY", "This cockpit is read-only manual paper support only.", category="safety"),
        _entry("ACCOUNT_AWARENESS=0", "This cockpit remains account-agnostic and read-only.", category="safety"),
        _entry("WAIT_FOR_RECLAIM", "Wait for reclaim confirmation before treating the setup as constructive again.", category="general"),
        _entry("WAIT_FOR_MARKET_RECLAIM", "Wait for broader market reclaim context before treating the setup as constructive again.", category="general"),
        _entry("NO_CHASE_WITHOUT_NEW_ZONE", "Do not chase current price without a fresh zone/map update.", category="general"),
        _entry("OPPORTUNITY_REVIEW", "Potential opportunity context for later review. Not permission.", category="general"),
        _entry("MOMENTUM_EXTENSION_REVIEW", "Momentum/extension context should be reviewed; it is not fresh entry permission.", category="general"),
        _entry("REFRESH_NEEDED_REVIEW", "Refresh/recompute review context is active.", category="general"),
        _entry("RECLAIM_REVIEW", "Reclaim context should be reviewed against the current map.", category="general"),
        _entry("SOFT_BLOCK", "Soft caution block. Review context only, not a hard veto by itself.", category="general"),
        _entry("HARD_BLOCK", "Harder block/caution context on the current dashboard.", category="general"),
        _entry("STALE_APLUS_CONTEXT", "A+ context exists but is stale, so it should be treated cautiously.", category="general"),
        _entry("BLOCK_SETUP_FILTER_FAIL", "Displayed policy block because the setup filter failed.", category="general"),
        _entry("BLOCK_RECOMPUTE_PENDING", "Displayed policy block because recompute is still pending.", category="general"),
        _entry("BLOCK_CHASE_RISK", "Displayed policy block because the setup is already too extended/chasey.", category="general"),
        _entry("BLOCK_SELECTION_NOT_ELIGIBLE", "Displayed policy block because selection state is not eligible.", category="general"),
        _entry("MARKET_CONTEXT_REVIEW", "Market context should be reviewed before promotion or action.", category="general"),
        _entry("MARKET_BREATH_EXPANSION_CONTEXT", "Market-breath context is in expansion / constructive regime.", category="general"),
        _entry("MARKET_BREATH_NEUTRAL_CONTEXT", "Market-breath context is neutral / mixed.", category="general"),
        _entry("MARKET_BREATH_RESET_CONTEXT", "Market-breath context is in reset / damaged regime.", category="general"),
        _entry("NEUTRAL_TRANSITION", "A+ / market-breath regime is transitioning through neutral context.", category="general"),
        _entry("COLLAPSE_RESET", "A+ / market-breath regime is in collapse/reset context.", category="general"),
        _entry("EXHALE_EXPANSION", "A+ / market-breath regime is in exhale-to-expansion context.", category="general"),
        _entry("FORMING", "Setup or context is still forming and not confirmed yet.", category="general"),
        _entry("RESET", "Reset context after a prior move / regime.", category="general"),
        _entry("CONFIRMED", "Displayed confirmation state is confirmed.", category="general"),
        _entry("HOLD", "Hold / monitor context for an existing map or position. Not an order.", category="position_review"),
        _entry("HOLD_MONITOR_TARGET", "Hold while monitoring target/reaction context. Not an order.", category="position_review"),
        _entry("WATCHLIST ONLY", "Watchlist/reference context only. Not a promoted setup.", category="candidate_readiness"),
        _entry("NO EDGE", "Displayed review says current setup does not have enough edge/quality.", category="candidate_readiness"),
        _entry("PULLBACK IN PROGRESS", "Current move is in pullback context rather than confirmation/continuation.", category="candidate_readiness"),
        _entry("REACTION RETEST", "Reaction/retest context is active around the mapped zone.", category="candidate_readiness"),
        _entry("ZONE_RECOMPUTE_NEEDED", "Current zone/map should be refreshed before relying on it.", category="add_buy_setup"),
        _entry("WAIT_RECOMPUTE", "Wait for a fresh zone/advice recompute before interpreting the row.", category="add_buy_setup"),
        _entry("WAIT_RECOMPUTE_FOR_INCREASE", "Do not increase until recompute confirms a fresh map/advice.", category="add_buy_setup"),
        _entry("ENTRY_ZONE_ACTIVE", "Entry zone is currently active around price.", category="zone_labels"),
        _entry("ENTRY_ZONE_PENDING", "Price is not yet in the mapped entry zone.", category="zone_labels"),
        _entry("ENTRY_ZONE_NEAR", "Price is near the mapped entry zone.", category="zone_labels"),
        _entry("IN_ENTRY_ZONE", "Price is currently inside the mapped entry zone.", category="zone_labels"),
        _entry("REACTION_ZONE_ACTIVE", "Reaction zone is currently active around price.", category="zone_labels"),
        _entry("REACTION_ZONE_PENDING", "Price is not yet in the mapped reaction zone.", category="zone_labels"),
        _entry("REACTION_ZONE_NEAR", "Price is near the mapped reaction zone.", category="zone_labels"),
        _entry("IN_REACTION_ZONE", "Price is currently inside the mapped reaction zone.", category="zone_labels"),
        _entry("SUPPORT_BELOW", "Below-price support/retest context. Not a take-profit target.", category="zone_labels"),
        _entry("RETEST_ZONE_BELOW", "Below-price retest/support context. Not a take-profit target.", category="zone_labels"),
        _entry("UPSIDE_REACTION_TARGET", "Above-price reaction target context. Not trade permission.", category="zone_labels"),
        _entry("UPSIDE_EXTENSION_PREVIEW", "Possible upside extension context. Requires fresh map/advice before action.", category="zone_labels"),
        _entry("DOWNSIDE_EXTENSION_PREVIEW", "Possible downside extension context after breakdown/continuation. Requires fresh map/advice before action.", category="zone_labels"),
        _entry("RECLAIM_NEXT_ZONE_PREVIEW", "Next-zone preview after reclaim/invalidation context. Market-only map preview, not trade permission.", category="zone_labels"),
        _entry("BREAKDOWN_NEXT_ZONE_PREVIEW", "Next-zone preview after breakdown/invalidation context. Market-only map preview, not trade permission.", category="zone_labels"),
        _entry("BREAKDOWN_RETEST_RESISTANCE", "Breakdown retest/resistance context after a downside move. Market structure context only.", category="zone_labels"),
        _entry("NEXT_UPSIDE_REACTION_TARGET", "Next upside reaction target preview after the current map is stale/finished.", category="zone_labels"),
        _entry("NEXT_UPSIDE_EXTENSION", "Next upside extension preview after the current map is stale/finished.", category="zone_labels"),
        _entry("NEXT_DOWNSIDE_REACTION_TARGET", "Next downside reaction target preview after breakdown context.", category="zone_labels"),
        _entry("NEXT_DOWNSIDE_EXTENSION", "Next downside extension preview after breakdown context.", category="zone_labels"),
        _entry("RECLAIM_RETEST_SUPPORT", "Reclaim retest/support context around a previously reclaimed level.", category="zone_labels"),
        _entry("DOWNSIDE_TARGET_SUPPORT_RETEST", "Support/retest context around a downside target zone.", category="zone_labels"),
        _entry("STRUCTURAL_INVALIDATION", "Structural invalidation level from the current map.", category="zone_labels"),
        _entry("TP / UPSIDE TARGET", "Displayed upside target zone from the current map.", category="zone_labels"),
        _entry("UPSIDE TP ZONE", "Displayed upside take-profit / target zone from the current map.", category="zone_labels"),
        _entry("DOWNSIDE TARGET", "Displayed downside target zone from the current map.", category="zone_labels"),
        _entry("DOWNSIDE ENTRY ZONE", "Displayed downside entry/reaction zone from the current map.", category="zone_labels"),
        _entry("ENTRY_FIB_PRIMARY_0500_0618", "Entry zone aligns with primary Fibonacci retracement band.", category="zone_labels"),
        _entry("TP_SR_ONLY", "Target is support/resistance only; historically weaker than near-fib extension context.", category="zone_labels"),
        _entry("TP_NEAR_FIB_EXTENSION", "Target is near a Fibonacci extension band; research scoreboard shows stronger separation than SR-only.", category="zone_labels"),
        _entry("DISPLAY_CRITICAL", "Highest review severity on the dashboard. The row still needs action now.", category="dashboard_display"),
        _entry("DISPLAY_WATCH", "Watch/cooldown severity on the dashboard. Refresh happened, but the row still needs monitoring.", category="dashboard_display"),
        _entry("DISPLAY_MUTED", "Muted display severity. Context is retained, but no active refresh action is implied now.", category="dashboard_display"),
        _entry("DISPLAY_CONTEXT", "Context-only dashboard severity. The row is shown for background reference.", category="dashboard_display"),
        _entry("ZONE_AND_ADVICE_RECOMPUTE", "Both the structural zone map and advice context should be refreshed.", category="recompute_lifecycle"),
        _entry("ADVICE_ONLY_REVIEW", "Advice context should be reviewed while structural zones can remain reference context.", category="recompute_lifecycle"),
        _entry("COOLDOWN_MONITOR", "This candle was already refreshed. Keep watching until the next 4h map can form.", category="recompute_lifecycle"),
        _entry("COOLDOWN_ALREADY_REFRESHED_THIS_CANDLE", "Refresh already ran for the current candle; do not treat age alone as a fresh action signal.", category="recompute_lifecycle"),
        _entry("RECOMPUTE_TRIGGER", "A lifecycle trigger requires a fresh recompute now.", category="recompute_lifecycle"),
        _entry("RECLAIM_OR_INVALIDATION_TRIGGER", "Reclaim or invalidation was touched, so a fresh zone/advice recompute is needed.", category="recompute_lifecycle"),
        _entry("TARGET_REACHED_STALE_TRIGGER", "Target reached on an old map; refresh before relying on any follow-through.", category="recompute_lifecycle"),
        _entry("TARGET_FINISHED_REVIEW", "Target was already finished; review context may still matter, but it is not a fresh entry map.", category="recompute_lifecycle"),
        _entry("FRESH_TARGET_REVIEW", "Target finished on a still-fresh map. Wait for the next candle before refreshing again.", category="recompute_lifecycle"),
        _entry("REFRESH_NEEDED", "Raw post-refresh classification: the row still needs refresh action.", category="recompute_lifecycle"),
        _entry("REFRESH_NEEDED_NOW", "Effective dashboard state: refresh action is still needed now.", category="recompute_lifecycle"),
        _entry("REFRESHED_RECENTLY", "A recent refresh was recorded; shown as background context unless the row is still triggering.", category="recompute_lifecycle"),
        _entry("REFRESHED_THIS_RUN", "The refresh pipeline updated this row in the current run.", category="recompute_lifecycle"),
        _entry("RECOMPUTED_BUT_STILL_TRIGGERING", "Refresh ran, but the row still immediately triggers the same recompute condition.", category="recompute_lifecycle"),
        _entry("STILL_TRIGGERING_AFTER_REFRESH", "Effective dashboard state: refresh already ran, but the trigger is still active.", category="recompute_lifecycle"),
        _entry("CURRENT_MAP_ACTIVE", "The current structural map is still active.", category="recompute_lifecycle"),
        _entry("ACTIVE_MAP", "Structural map remains active without recompute requirement.", category="recompute_lifecycle"),
        _entry("SKIP_ACTIVE_MAP", "No recompute work is needed because the current map is still active.", category="recompute_lifecycle"),
        _entry("NO_REFRESH_NEEDED", "Raw post-refresh classification: no refresh action is needed now.", category="recompute_lifecycle"),
        _entry("WAIT_FOR_NEXT_CANDLE", "Wait for the next candle before requesting another refresh.", category="recompute_lifecycle"),
        _entry("WAIT_NEXT_4H_MAP", "Effective dashboard state: this candle is already refreshed, so wait for the next 4h map.", category="recompute_lifecycle"),
        _entry("ALREADY_REFRESHED_THIS_CANDLE", "Effective dashboard state: this candle already has a refresh record.", category="recompute_lifecycle"),
        _entry("DOWN_MAP_INVALIDATED_BY_RECLAIM", "A down-leg map was invalidated by reclaim, so the map should be refreshed.", category="recompute_lifecycle"),
        _entry("MAP_RECOMPUTE_NEEDED", "Lifecycle context says the current map needs recompute.", category="recompute_lifecycle"),
        _entry("TARGET_OVERSHOT", "Price moved through the mapped target enough that the map should be reviewed/refreshed.", category="recompute_lifecycle"),
        _entry("INVALIDATION_TOUCHED", "Price touched the mapped invalidation boundary.", category="recompute_lifecycle"),
        _entry("UP_MAP_INVALIDATED_BY_BREAKDOWN", "An up-leg map was invalidated by breakdown.", category="recompute_lifecycle"),
        _entry("SKIP_UNKNOWN_DATA", "The row is skipped from refresh action because key context is unknown or missing.", category="recompute_lifecycle"),
        _entry("UNKNOWN_DATA", "Key map or price context is unknown.", category="recompute_lifecycle"),
        _entry("NO_REFRESH_TRIGGER", "No refresh trigger was found in the current row context.", category="recompute_lifecycle"),
        _entry("REFRESH_FAILED_OR_STALE", "Refresh did not land cleanly or the refreshed result is already stale.", category="recompute_lifecycle"),
        _entry("RECLAIM_CONFIRMED", "Reclaim condition was confirmed against the current map.", category="recompute_lifecycle"),
        _entry("DOWNSIDE_TARGET_REACHED", "Downside target/support was reached on the mapped move.", category="recompute_lifecycle"),
    ]
}


def get_label_metadata(label: str) -> LabelDescription:
    normalized = str(label or "").strip().upper()
    if not normalized:
        return LabelDescription("", UNKNOWN_LABEL_DESCRIPTION)
    return _REGISTRY.get(normalized, LabelDescription(normalized, UNKNOWN_LABEL_DESCRIPTION))


def get_label_description(label: str) -> str:
    return get_label_metadata(label).description


def get_label_aria_label(label: str) -> str:
    text = str(label or "").strip()
    if not text:
        return UNKNOWN_LABEL_DESCRIPTION
    return f"{text}: {get_label_description(text)}"


def get_label_human_label(label: str) -> str:
    metadata = get_label_metadata(label)
    return metadata.human_label or str(label or "").strip()


def get_label_axis_value(label: str, axis_name: str) -> int | None:
    metadata = get_label_metadata(label)
    if metadata.axis_name != axis_name:
        return None
    return metadata.axis_value


def is_label_registered(label: str) -> bool:
    normalized = str(label or "").strip().upper()
    return bool(normalized) and normalized in _REGISTRY
